spring.application.name=monitoramento-entregas-api

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/entregas_api
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Console H2 (Desativado)
spring.h2.console.enabled=false

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Comando para a jpa criar a tabela e tbm atualizar ela automaticamente
spring.jpa.hibernate.ddl-auto=update
