create table entregadores (
    id bigint generated by default as identity,
    nome varchar(255) not null,
    status varchar(255) not null check ((status in ('DISPONIVEL','EM_ENTREGA','OFFLINE'))),
    telefone varchar(255) not null unique, primary key (id));
create table entregas (
    data_conclusao timestamp(6),
    data_inicio timestamp(6),
    entregador_id bigint not null,
    id bigint generated by default as identity,
    pedido_id bigint not null,
    status varchar(255) not null check ((status in ('CRIADO','AGUARDANDO_ENTREGADOR','EM_ROTA','ENTREGUE','CANCELADO','FALHA'))),
    primary key (id));
create table localizacoes (
    latitude float(53) not null,
    longitude float(53) not null,
    data_hora timestamp(6) not null,
    entrega_id bigint not null,
    id bigint generated by default as identity, primary key (id));
create table pedidos (
    data_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    cep varchar(255) not null, cliente varchar(255) not null,
    endereco_entrega varchar(255) not null,
    status varchar(255) not null check ((status in ('PENDENTE','EM_ROTA','ENTREGUE','CANCELADO','FALHA'))),
    primary key (id));
alter table if exists entregas add constraint fk_entrega_entregador foreign key (entregador_id) references entregadores;
alter table if exists entregas add constraint fk_entrega_pedido foreign key (pedido_id) references pedidos;
alter table if exists localizacoes add constraint fk_localizacao_entrega foreign key (entrega_id) references entregas;
